// GENERATED by backend/src/scripts/build-guide-content.ts from backend/content/guides/*.md.
// Nie edytuj ręcznie: zmień plik .md i uruchom `npx tsx src/scripts/build-guide-content.ts` w backend/.

/** Ścieżki poradników — trasy statyczne mają pierwszeństwo przed /leasing/:slug (oferty). */
export const GUIDE_PATHS: string[] = [
    "/leasing/limity-podatkowe-2026",
    "/leasing/vat"
];

/** Lista do bloku „Czytaj też” (bez treści — treść przychodzi z API/SSR). */
export const GUIDES_INDEX: Array<{ path: string; hub: string; breadcrumb: string; h1: string }> = [
    {
        "path": "/leasing/limity-podatkowe-2026",
        "hub": "/leasing",
        "breadcrumb": "Limity kosztów 2026",
        "h1": "Limit 100 tys. zł w leasingu od 2026 r.: limity podatkowe samochodu osobowego"
    },
    {
        "path": "/leasing/vat",
        "hub": "/leasing",
        "breadcrumb": "Samochód w firmie a VAT",
        "h1": "Samochód w firmie a VAT: odliczenie 50% czy 100%, VAT-26 i ewidencja przebiegu"
    }
];
